### ISSUE TITLE
zrange return

### ISSUE THREAD

**Issue by dmiljkovic** [jkaye2012/Redis.jl#12]
Hi there,

Thanks for providing support for Redis!!!

I think that ordered sets should return array not the Set. By returning the Set from zrange we are loosing order which is the key reason to use ordered sets.

Dejan

**Comment by sbromberger** [comment]
:+1 - I wonder if we can use an OrderedSet or something for this (OrderedSets use insertion order which may make sense if we're pulling results directly from redis output, since they'll be sorted already).

**Comment by jkaye2012** [comment]
Definitely think this makes sense. I'll try to find some time to take a look at this this weekend. Thanks for the feedback!

--Jordan

**Comment by jkaye2012** [comment]
Addressed in ad4b60cd18085b8bb5dc05538d8a6bc4282ccea1.
