### ISSUE TITLE
Base.String is deprecated

### ISSUE THREAD

**Issue by stefanks** [jkaye2012/Redis.jl#15]
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /Users/stepa/.julia/v0.4/Redis/src/exceptions.jl:4

and elsewhere

**Comment by jkaye2012** [comment]
Thanks for the feedback. I will address this for 0.0.3

**Comment by jkaye2012** [comment]
Fixed in b78cf3dc4f7677c224c8c837cc6ef3866008e3ed
