### ISSUE TITLE
Consider moving to JuliaDB?

### ISSUE THREAD

**Issue by sbromberger** [jkaye2012/Redis.jl#19]
I notice that there's an effort to provide various database interfaces at https://github.com/JuliaDB. I'd suggest that Redis.jl is a pretty solid candidate for inclusion there.

**Comment by jkaye2012** [comment]
I wasn't aware this existed. I agree, it would be nice to include Redis.jl alongside other database clients. I'm all for inclusion, provided the maintainers agree of course :)

**Comment by jkaye2012** [comment]
A move to JuliaDatabases is in progress.
