### ISSUE TITLE
EXEC not defined

### ISSUE THREAD

**Issue by merl-dev** [jkaye2012/Redis.jl#2]
When testing transactions we get the following error (I have obfuscated our host ip):
julia> using Redis

julia> using Base.Test

julia> trans = open_transaction(conn)
TransactionConnection("<our-host-ip>",6379,"",0,TcpSocket(active, 0 bytes waiting))

julia> @test set(trans, "testkey", "foobar") == "QUEUED"

julia> @test get(trans, "testkey") == "QUEUED"

julia> @test exec(trans) == ["OK", "foobar"]
ERROR: test error during exec(trans) == ["OK","foobar"]
EXEC not defined
 in exec at /home/ubuntu/.julia/v0.3/Redis/src/commands.jl:298
 in anonymous at test.jl:62
 in do_test at test.jl:37

julia> disconnect(trans)

**Comment by jkaye2012** [comment]
This was an oversight after my previous changes, sorry!

3e1dfb93b5dc174318aac308d46493a900fbc2c2
