### ISSUE TITLE
Warning when loading the package, update needed for 0.4?

### ISSUE THREAD

**Issue by jiningq** [jkaye2012/Redis.jl#20]
When I do 
> using Redis

There are like 20 warnings saying
>WARNING: Base.String is deprecated, use AbstractString instead.

I guess there's some small modification needed to comply with v0.4, but I could be wrong.

**Comment by jiningq** [comment]
Oh and when I do
>conn = RedisConnection()

There is 
>WARNING: Base.TcpSocket is deprecated, use Base.TCPSocket instead.

**Comment by jkaye2012** [comment]
These issues are all resolved at the head of master, but the tests show a regression in nb_available in v0.4 which breaks subscription so I haven't tagged the latest version yet. 

Once I receive some response from the Julia team about this, v0.0.3 will be available.

--Jordan

**Comment by jiningq** [comment]
Thanks for the response and thanks for the good work!
