### ISSUE TITLE
set() function's, String dependency

### ISSUE THREAD

**Issue by dogabudak** [jkaye2012/Redis.jl#21]
I am calculating some realtime data via julia , but after i finish my process i have to convert this data to protocol buffers than set it to redis. 
The :value field of the set() function at redis.jl only works with String data, i know, but after i convert my binary data to string then set it to redis,  reading it again from another environment (such as javascript), it fails!

Let me write an example code also ;

```julia

using ProtoBuf
using Redis

             type MyType 
                intval::Int
                strval::AbstractString
                MyType() = new()
                MyType(i,s) = new(i,s)
              end

iob = PipeBuffer();
writeproto(iob,MyType(10,"Hello_world"))

conn = RedisConnection(;host="127.0.0.1", port=6371, db=1)

set(conn, "doga", string(iob.data))    ## instead iob.data i have tried many other variations also 

```

Do you have any suggestions about this matter ? Or can u give me any advice about how should i do it.

**Comment by jkaye2012** [comment]
Hi there.

I haven't worked with Protobuf in Julia before, but I think if you use bytestring instead things might work as you're expecting.

`set(conn, "doga", bytestring(iob.data))`

My expectation is that this is an encoding issue. You would also have to make sure that you're reading the bytestring in properly on the other side.

If that doesn't work, could you please send the code snippet from the other side along with the error message?

Hope that helps,
Jordan

**Comment by sbromberger** [comment]
I haven't used ProtoBuf, but looking at the docs I don't think you're using it correctly. You shouldn't be accessing `iob` in any case except to read it back into a type `MyType`, after which you can access `strval` normally.

**Comment by jkaye2012** [comment]
Actually, I would suggest against creating a custom serialization. Redis and Protobuf play very well together. `iob` here is just a pipe buffer, so accessing it shouldn't really be a big deal. If I read their docs correctly, `iob` is just holding the serialized representation of the Protobuf instance, so as long as you're not modifying the serialized data it should be fine.

**Comment by sbromberger** [comment]
After going through the protobuffer docs, I agree with @jkaye2012 - this looks like a great solution. The only thing I can think of is that the serialized data may not be string-representable and therefore needs to be stored in redis as some other data type.

**Comment by dogabudak** [comment]
After running some tests, i found out that  bytestring() do actually work when writing to redis. But about reading it back it still gives me error at javascript, i should run more tests.I will make another test case,  instead of using protocol buffers i will use custom byte array. I will share the results of it shortly.

**Comment by jkaye2012** [comment]
Closing this for now as it doesn't seem to be an issue with Redis.jl. Feel free to message me if you need further help.

--Jordan
