### ISSUE TITLE
Using pipeline

### ISSUE THREAD

**Issue by NaelsonDouglas** [jkaye2012/Redis.jl#22]
Hello,
We know Redis has suport to pipelines
http://redis.io/topics/pipelining

I'd like to know if there's an implementation to Redis.jl for pipelining too. Since we used the Ruby Redis code with this feature and we had a better result(less time to load the data) than using the same code on the Julia implementation
Ruby: https://gist.github.com/raphapr/2ced51ce5b8a6eedf4af

Julia: https://gist.github.com/raphapr/ecd238436021157805ea

Thanks

**Comment by jkaye2012** [comment]
Hi there,

Seems like I missed this functionality originally! I've added it this morning: 9a9f44bf06d06bd99600695f7d7073e019e5410e

Quick example:

```julia
conn = RedisConnection()
pipeline = open_pipeline(conn)
NUM_ENTRIES = 1000000
MAX_VAL = 12000000

for i in 1:NUM_ENTRIES
    hset(pipeline,"hash","$i:$i",i)
end

disconnect(pipeline)
```

Using this, I get a benchmark of ~30 seconds on my machine. Could you pull down this version and give it a try in your environment?

Thanks,
Jordan

**Comment by raphapr** [comment]
Awesome @jkaye2012! I get 43 seconds on my machine using your code. Thanks for your work.

` 43.476365 seconds (147.62 M allocations: 6.312 GB, 1.51% gc time) `

**Comment by NaelsonDouglas** [comment]
Hi, @jkaye2012 

I'm working with @raphapr , so his test also goes to me.

Thanks for the quick answer and VERY quick solution, we really appreciate it. You are the best.

Naelson

**Comment by proflage** [comment]
Thank you @jkaye2012 for this fix.

Do you guys have any clue what Ruby Redis Client beats Redis.jl?

I mean, by using pipeline Ruby code performance was 21.406534202 seconds while Julia code performance was 43.476365 secs.

@raphapr are you sure you ran these codes with the same configuration (e.g., same machine and no other coding was heavily disputing the CPU)?

**Comment by jkaye2012** [comment]
I can take a look and do a little bit of benchmarking this week. Most likely the reason is that Redis.jl isn't really optimized at all yet - I originally wrote everything to be as simple as possible. I wouldn't be too surprised to find some inefficiencies in the current implementation. It's something I'd like to focus on more in the coming months, but just haven't had too much time for quite yet.

--Jordan

**Comment by raphapr** [comment]
Yes @proflage, same system/machine/configuration.

**Comment by jkaye2012** [comment]
Unless there's anything else to do here, I'm probably going to close this and tag the new version some time today or tomorrow. We can open another issue for performance enhancements some time in the future, I think.

--Jordan

**Comment by proflage** [comment]
hi @jkaye2012 

I think it's more appropriate to open a new issue on performance enhancements and close this one as Redis.jl provides pipelining.

@raphapr could you please open this new issue?

**Comment by jkaye2012** [comment]
Resolved.

**Comment by proflage** [comment]
Thanks @jkaye2012.
