### ISSUE TITLE
Read data using pipeline

### ISSUE THREAD

**Issue by NaelsonDouglas** [jkaye2012/Redis.jl#24]
Let's say I create a pipeline like this
conn = RedisConnection()
pipeline = open_pipeline(conn)
rpush(pipeline,"a")
rpush(pipeline,"b")
rpush(pipeline,"c")
rpush(pipeline,"d")

But when I try to use lrange on this pipeline, I don't get the output
lrange(pipeline,"list", 0,-1)

I still can get the data using lrange(conn,"list", 0,-1), but when using the pipeline I only get an integer number.

Is there a way to get theses values via pipeline?

**Comment by jkaye2012** [comment]
Hi there,

The pipeline can be read using the `read_pipeline` method. Is that not working for you, or is there something else that you need that isn't provided?

--Jordan

**Comment by NaelsonDouglas** [comment]
Looks like I was using that in the wrong way. Thanks for your attention.
