### ISSUE TITLE
returning `nothing` from GET to indicate "not found" can be awkward

### ISSUE THREAD

**Issue by JeffreySarnoff** [jkaye2012/Redis.jl#26]
There may be a simliarly easy-to-use alternative that keeps Redis.jl users happy and plays well.

[please see this thread in julia-users for the discussion](https://groups.google.com/forum/#!topic/julia-users/FLu3ajWLkpU)

**Comment by jkaye2012** [comment]
Any suggestions? I'm not against making changes if it cleans up the API.

**Comment by merl-dev** [comment]
There is definitely a type-stability issue when returning `nothing` for non-existent keys.  However, introducing a `Nullable` into the equation, would in my opinion,  make things worse (more complicated for existing production implementations). The Redis interface is string-based, but as quoted in the user discussion link above:
> The client library API should not return an empty string, but a nil object, when the server replies with a Null Bulk String. For example a Ruby library should return 'nil' while a C library should return NULL (or set a special flag in the reply object), and so forth.

Julia has its own strict requirements regarding type-stability, regarding a similar issue:
>One could write the sqrt() function to switch to a complex-valued output only when passed a negative number (which is what sqrt() does in some other languages), but then the result would not be type-stable and the sqrt() function would have poor performance.

So, IMHO, an empty string would be better than the current practice of returning `nothing`

**Comment by merl-dev** [comment]
Another related issue, `hgetall` returns a Dict{AbstractString, AbstractString}, `hkeys` and `hvals return Array{Any,1}.  I'll be making a PR in the next few days with suggested fixes for these issues.

**Comment by ylxdzsw** [comment]
There is a difference between `Null Bulk String` and `Empty Simple Strings` in Redis, but we cannot recognize them if all become `""` in julia. That means, if a user saved an empty string, you need to do additional checks to distinguish it from "really empty" records. So I am against the idea of using empty strings as return value.

**Comment by merl-dev** [comment]
Good point!  Maybe we should really consider `Nullable`s when encountering `nil`. As I work through testing all the available commands this option is starting to make more and more sense.

**Comment by jkaye2012** [comment]
I definitely agree with @ylxdzsw here. We should try to come up with a solution that will avoid ambiguity while solving the `nothing` issues. I think that `Nullable` is probably the right path; this would be a breaking API change and would lead us to v0.2.0

**Comment by jkaye2012** [comment]
These have been resolved with a type union in the latest version
