### ISSUE TITLE
Unsubscribe doesn't work with Julia 0.4.6

### ISSUE THREAD

**Issue by LouisMagarshack** [jkaye2012/Redis.jl#37]
Hi,

when running `unsubscribe(foo, "bar")` I get the following error:
```LoadError: MethodError: `unshift!` has no method matching unshift!(::Tuple{ASCIIString}, ::ASCIIString)
Closest candidates are:
  unshift!(::Any, ::Any, !Matched::Any)
  unshift!(::Any, ::Any, !Matched::Any, !Matched::Any...)
  unshift!{T}(!Matched::Array{T,1}, ::Any)```

I believe this could be fixed by changing the last line of `unsubscribe` to:
`execute_command(conn, unshift!(collect(channels), "unsubscribe"))`.

Would this have any adverse side effects?

**Comment by merl-dev** [comment]
I'm looking inot the issue now and getting same error with 0.5, but note that your proposed solution doesn't seem to work, leaves the client blocked.

**Comment by LouisMagarshack** [comment]
Hm that change works for me on 0.4, I'm not sure what could cause the client to hang...
Having said that I haven't tried on 0.5 : )

**Comment by merl-dev** [comment]
Redis.jl as is on julia 0.5 is painfully slow and some of the commands as implemented have issues.  See my comment https://github.com/jkaye2012/Redis.jl/issues/38.

**Comment by merl-dev** [comment]
The previously mentioned hiredis branch at https://github.com/merl-dev/Redis.jl/commit/8a29d4f225a41ee301ae99670d688bb774906130 now runs pub-sub smoothly and will pass all tests locally (but fails travis for some opaque reason). 

For use take a look at redis_tests.jl and make sure to unsubscribe all channels before exiting Julia.

**Comment by LouisMagarshack** [comment]
Thank you!
