### ISSUE TITLE
RedisConnection not defined in version 0.0.1

### ISSUE THREAD

**Issue by yeison** [jkaye2012/Redis.jl#4]
When I install Redis via Pkg.add("Redis") I get version 0.0.1.  Creating a RedisConnection() returns a message that RedisConnection() is not defined.

I only managed to get it to work with Pkg.clone("https://github.com/jkaye2012/Redis.jl.git")

At this point it's still version 0.0.1 that's installed, but this way it works.

**Comment by jkaye2012** [comment]
I've been unable to reproduce this. Just installed Julia (v0.3.7) on a fresh virtual machine and ran

```
Pkg.add("Redis")
using Redis
r = RedisConnection()
get(r, "testkey")
```

and everything worked as expected. Can you reproduce this in multiple environments?

**Comment by yeison** [comment]
Sorry, it was completely my fault.  I'm using Juno and Juno uses Julia v0.3.4.  I wasn't aware.  The problem only occurs if I load Pkg.add("Redis") from Juno itself.  The Redis version shows up as 0.0.- 

I was able to resolve it by deleting the Redis from my package directory and installing again using Pkg.add("Redis") from a v0.3.7 Julia REPL
