### ISSUE TITLE
String value being truncated

### ISSUE THREAD

**Issue by stugorf** [jkaye2012/Redis.jl#42]
I am using set(connection, key, value) via RedisConnection where value is a 13.923 KB string (13,917 characters). The string is getting truncated to 13.917 KB (13,911 characters). Have you seen this before?

**Comment by stugorf** [comment]
I set the logging level in Redis to `vebose` and now can see this error with any set(k,v):
```
Protocol error from client: id=8 addr=172.17.0.1:54068 fd=8 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=6 qbuf-free=32762 obl=56 oll=0 omem=0 events=r cmd=set
```

**Comment by merl-dev** [comment]
Could you be more specific about the version you're using and provide a complete example, as I am unable to reproduce this using the current tagged version of Redis.

**Comment by merl-dev** [comment]
Rather than wait, I ran some tests using the tagged version:
```
julia> using Redis
WARNING: symbol is deprecated, use Symbol instead.

julia> conn = RedisConnection()
Redis.RedisConnection("127.0.0.1",6379,"",0,TCPSocket(open, 0 bytes waiting))

julia> flushdb(conn)
"OK"

julia> keys(conn, "*")
Set{Any}()

julia> s=randstring(10^6);

julia> sizeof(s) == 10^6
true

julia> set(conn, "tests", s)
true

julia> a=get(conn, "tests");
WARNING: readbytes is deprecated, use read instead.
 ...

julia> a==s
true
```

As you can see there were no issues, and none were found in the log file /var/log/redis_6379.log with verbose on.  

As an aside, I would suggest you run `Pkg.checkout("Redis")` and run your own tests to see if that doesn't solve your issue.

**Comment by stugorf** [comment]
Hi,

 

Turns out the issue may be with the JSON value being passed in to Redis. I confirmed the JSON was well formed but tried escaping it anyway along with other methods of wrapping the string format of the JSON package I was trying to store. In the end I base64 encoded the string JSON and that solved the issue. So the final solution is JSON -> base64encode -> Redis -> base64decode -> JSON

 

Thank you,

 

_David

**Comment by merl-dev** [comment]
```
julia> using Requests

julia> r = get("http://echo.jsontest.com/key_1/100/key_2/200")
Response(200 OK, 10 headers, 41 bytes in body)

julia> string_json = String(r.data)
"{\n   \"key_2\": \"200\",\n   \"key_1\": \"100\"\n}\n"

julia> a_dict = JSON.parse(string_json)
Dict{String,Any} with 2 entries:
  "key_1" => "100"
  "key_2" => "200"

julia> set(conn, "testjson", string_json)
"OK"

julia> get(conn, "testjson") == string_json
true

julia> JSON.parse(get(conn, "testjson")) == a_dict
true
```
