### ISSUE TITLE
Plans for v0.6?

### ISSUE THREAD

**Issue by smldis** [jkaye2012/Redis.jl#43]
Hello,
Are there any plans for Julia 0.6?
Is there someone already working on it?

Thank you,
 smldis

**Comment by merl-dev** [comment]
Yes, I have been working on an 0.6 upgrade for the last 2-3 weeks.  Almost all of the current Redis.jl API remains mostly unchanged and it has passed all tests.  It is type-stable, much faster, and includes GeoSets, Cluster commands, more Sentinel commands, and implements Julia's scan iterator interface for *SCAN Iterators.  

Still need to work out some issues with scripting, add test suites for Sentinel and Cluster, rewrite chunks of the documentation, and do some refactoring.  Should be ready to make a pull request latest by early next week. You can see a preview at https://github.com/merl-dev/Redis.jl/tree/typestable0.6. Any comments and issues before then (or after) would be very much appreciated.

**Comment by merl-dev** [comment]
see my comment https://github.com/jkaye2012/Redis.jl/issues/44
