### ISSUE TITLE
Plans to update to 0.6?

### ISSUE THREAD

**Issue by klensink** [jkaye2012/Redis.jl#46]
I'm thinking of trying to interactive with a Redis server in one of my Julia packages. 

Do you have any plans to update this package to 0.6?

Thanks

**Comment by merl-dev** [comment]
I have a branch at https://github.com/merl-dev/Redis.jl/tree/typestable0.6?files=1 that runs well under v.0.6.  The backend relies on the hiredis c lib for performance, and handles 'nil' values.  It's been on hold for the last few months until julia 0.7/1.0 is released and I come up with a definitive solution for handling nulls.

**Comment by klensink** [comment]
Thanks for pointing me towards your Redis.jl branch, I'm going to clone it and play around with it today. I was worried about the performance of the pure Julia implementation of Redis.jl, so I'm excited to see that your branch makes us of the C lib.

In the meantime I've crudely updated a [fork of HiRedis.jl ](https://github.com/slimgroup/HiRedis.jl) to v0.6, and have got most of the functionality working.
